# Generated by Django 2.1.2 on 2018-11-13 19:23

import device.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20181112_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hardware',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=device.models.Hardware),
        ),
    ]
