# Generated by Django 2.1.2 on 2018-11-13 21:59

import device.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=device.models.Hardware, null=True),
        ),
    ]
