# Generated by Django 2.1.2 on 2018-11-21 23:03

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_device_hardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', djongo.models.fields.DictField(default={})),
                ('num_samples', models.IntegerField(default=0)),
                ('total_samples', models.FloatField(default=0.0)),
                ('timestamp_hour', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterfaceStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('sitename', models.CharField(blank=True, max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField()),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='netmask',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_polling_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='snmp_polling_local_interval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
        migrations.AddField(
            model_name='deviceinterfacestatushistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
        migrations.AddField(
            model_name='cpuhistory',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device'),
        ),
    ]
