# Generated by Django 2.1.1 on 2018-09-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_auto_20180916_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
